name: Continuous Integration and Delivery

on: 
  push:
    branches:
      - master

env:
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY)/app

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to Github Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin https://ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build Image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag version0 \
            --file ./src/Dockerfile.prod \
            "./src"
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:version0
  
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build]
    env:
      HEROKU_APP_NAME: birds-and-climate-app
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/app
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to Github Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin https://ghcr.io
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:version0 || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:version0 \
            --tag ${{ env.HEROKU_REGISTRY_IMAGE }}:version0 \
            --file ./src/Dockerfile.prod \
            "./src"
      - name: Log in to the Heroku Container Registry
        run: docker login -u _ -p ${HEROKU_AUTH_TOKEN} registry.heroku.com
        env:
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      - name: Push to the registry
        run: docker push ${{ env.HEROKU_REGISTRY_IMAGE }}
      - name: Set environment variables
        run: |
          echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> $GITHUB_ENV
          echo "HEROKU_AUTH_TOKEN=${{ secrets.HEROKU_AUTH_TOKEN }}" >> $GITHUB_ENV
      - name: Release
        run: |
          chmod +x ./release.sh
          ./release.sh
